### PR TITLE
Initial commit : Intro

### PR DESCRIPTION
**Pull request by Kemist24**

### CODE REVIEW

**Comment by Panku51** [comment]
you need to add this intro file in your name folder

**Comment by Kemist24** [comment]
How to do that?

**Comment by Kemist24** [comment]
Already made

**Comment by Panku51** [comment]
But you pushed only the intro file. Let’s check it once otherwise i will assist you

**Comment by Kemist24** [comment]
Sorry but I cannot understand all of it, first time using git hub.
 Is there a yt video where all of this process is explained can you send a link of such video

Thank you for your time sir.

**Comment by Panku51** [comment]
Kindly Dm me on whatsapp.

**Pull request closed without merging**
